### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by vastronghq** [katerinavr/cocrystals#1]
I am very interested in your work. May I ask if you have published the relevant paper? Thank you！

**Comment by katerinavr** [comment]
Hello, 
Thank you for you email! Yes, this work has been recently publised in digital discovery: https://pubs.rsc.org/en/content/articlelanding/2022/dd/d2dd00068g . 
I also attach the paper in pdf.
Kind regards,Katerina
    Στις Παρασκευή 28 Οκτωβρίου 2022 - 07:58:41 π.μ. GMT-5, ο χρήστης rewquiofds ***@***.***> έγραψε:  
 
 


I am very interested in your work. May I ask if you have published the relevant paper? Thank you！

**Comment by vastronghq** [comment]
Thank you for your prompt reply！👍
